services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
      - WEBUI_LOCALHOST_AUTH=false
    volumes:
      - /tmp:/downloads
      - ./config:/config
      - ./ensure_config.sh:/custom-cont-init.d/10-qbittorrent-config.sh # Ensure auth disabled in config
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
